apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-reader
# subjects:
# - kind: ServiceAccount
#   name: foo
#   namespace: foo
subjects:
- kind: User
  name: foo
  namespace: foo
  apiGroup: rbac.authorization.k8s.io