apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    type: Container
    min:
      cpu: 200m
      memory: 128Mi
    max: 
      cpu: 800m
      memory: 1Gi