apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - image: alextanhongpin/kube-node
    imagePullPolicy: IfNotPresent
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP